---
title: "Last lab"
author: "Damiche Inès"
format: html
editor: visual
---

# Preparation

```{r}
here::i_am("bt_empire.Rproj")
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
library(here)
```

# Link to the github repository

<https://github.com/inesdamiche/bt_empire.git>

# Question 1
done 

# Question 2
done 

# Question 3

```{r}
systems <- vroom(here("data/The_systems.csv"), locale(decimal_mark = ","))
#read.csv("data/The_systems.csv", header = TRUE, sep = ";", dec = ",",stringsAsFactors = FALSE)

is.numeric(systems$Star_idx)
is.numeric(systems$`DISTANCE (LIGHTYEARS)`)
is.numeric(systems$`effective temperature`)
is.numeric(systems$`RELATIVE MASS`)
is.numeric(systems$`Star Radius`)
is.numeric(systems$`Relative Luminosity`)
```

# Question 4

```{r}
systems |> 
  summarise("nb of observations" = nrow(systems), "nb of variables" = ncol(systems))|>
  mutate("nb of obs with at least one NA" = sum(rowSums(is.na(systems)) > 0))|>
  knitr::kable()

knitr::kable(colSums(is.na(systems)))

```

# Question 5

```{r}
systems |>
  ggplot(aes(x = `RELATIVE MASS`, y = `effective temperature`)) + geom_point(alpha = 0.1)
```

# Question 6

## DISTANCE

```{r}
min_distance <-
  systems |>
  slice_min(`DISTANCE (LIGHTYEARS)`) 
min_distance <- min_distance[2]

max_distance <-
   systems |>
    slice_max(`DISTANCE (LIGHTYEARS)`)
max_distance <- max_distance[2]

df_distance <- data.frame(
  Column1 = c(min_distance),
  Column2 = c(max_distance)
)


knitr::kable(df_distance, col.names = c("min distance", "max distance")) 

```

## TEMPERATURE 

```{r}
min_temp <-
  systems |>
  slice_min(`effective temperature`) 
min_temp <- min_temp[2]

max_temp <-
   systems |>
    slice_max(`effective temperature`)
max_temp <- max_temp[2]

df_temp <- data.frame(
  Column1 = c(min_temp),
  Column2 = c(max_temp)
)


knitr::kable(df_temp, col.names = c("min temperature", "max temperature")) 
```

## RELATIVE MASS

```{r}
min_mass <-
  systems |>
  slice_min(`RELATIVE MASS`) 
min_mass <- min_mass[2]

max_mass <-
   systems |>
    slice_max(`RELATIVE MASS`)
max_mass <- max_mass[2]

df_mass <- data.frame(
  Column1 = c(min_mass),
  Column2 = c(max_mass)
)


knitr::kable(df_mass, col.names = c("min mass", "max mass")) 
```

## STAR RADIUS 

```{r}

```

## RELATIVE LUMINOSITY 
```{r}

```

# Question 7 
done

# Question 8 
```{r}
factions <- vroom(here("data/the%factions.csv"))
cntrl_factions <- vroom(here("data/Btfactionsystem.csv"))
```

# Question 9

```{r}
nb_A <- sum(cntrl_factions $`fkey`== "A")
nb_I <- sum(cntrl_factions $`fkey`== "I")
nb_U <- sum(cntrl_factions $`fkey`== "U")

df1 <- data.frame(variable = c("Nb of A", "Nb of I", "Nb of U"), count = c(nb_A, nb_I, nb_U))
knitr::kable(df1)
```

# Question 10 




